v0.8i1

diff --git a/install b/install
--- a/install
+++ b/install
@@ -40,11 +40,11 @@ fi
 
 if [ -e `which ldconfig` ]; then
 	ldconfig
-fi
 
-if [ $? -ne 0 ]; then
-	echo "Failed to execute ldconfig"
-	exit 1;
+	if [ $? -ne 0 ]; then
+		echo "Failed to execute ldconfig"
+		exit 1;
+	fi
 fi
 
 echo "Installation complete."
